### ISSUE TITLE
print in bold, underline.

### ISSUE THREAD

**Issue by kannanrs** [JoshyFrancis/VB6-Print-Class#1]
Hi there..
great library to use with after a long time..

help me with printing in bold and center the words in a line, unerlining a word

TIA

Kannan

**Comment by JoshyFrancis** [comment]
Use selectobject,createFont and  DrawText API functions

**Comment by kannanrs** [comment]
Thank you for the reply... Can you share a sample please...


TIA
Kannan

**Comment by JoshyFrancis** [comment]
Download this project and extract
and in frmAPIPrint declarations section:-

Private Declare Function TextOutW Lib "gdi32" (ByVal hdc As Long, ByVal x As Long, ByVal y As Long, ByVal lpString As Long, ByVal nCount As Long) As Long

Add a command button : -

Private Sub Command1_Click()
                Erase Pages
                PageCount = 0
        cp.Preview = True
If cp.PrinterStartDoc Then
        cp.PrinterStartPage
                'cp.PrintText "Hello", 10, 10
            cp.Rectangle 1, 1, cp.Width - 2, cp.Height - 2
        Dim f As New StdFont
            f.Name = "Times New Roman"
            f.Size = 200
            f.Bold = True
            f.Underline = True
                    
                    Set cp.Font = f
'                cp.PrintText "Page 1 " + ChrW(3374), cp.Width \ 2 - cp.TextWidth("Page 1") \ 2, 1
            Dim str As String
                str = "See Unicode " + ChrW(3374) + ChrW(3378) + ChrW(3375) + ChrW(3390) + ChrW(3379) + ChrW(3330)
           TextOutW cp.hdc, cp.Width \ 2 - cp.TextWidth("Page 1") \ 2, 1, StrPtr(str), Len(str)
            cp.PaintTo Picture1.hdc, Picture1.ScaleWidth, Picture1.ScaleHeight
                Picture1.Refresh
                   
        cp.PrinterEndPage
    cp.PrinterEndDoc
End If
        cp.Preview = False
        
End Sub

Now you can see the print preview.
you can send document  to printer by turning off cp.Preview = False instead of cp.Preview = True

**Comment by JoshyFrancis** [comment]
![image](https://user-images.githubusercontent.com/13165076/113659100-f0a17d80-96be-11eb-8c6b-fab590118224.png)

**Comment by JoshyFrancis** [comment]
@kannanrs Please let me know your issue is solved.

**Comment by JoshyFrancis** [comment]
Closing issue of inactivity, assuming issue is solved.

**Comment by kannanrs** [comment]
Hi there,,


Thank you for the guide...
I'm yet to update because of the lockdown and other issues here...


Thank you once again...



Kannan
